spring:
  profiles:
    active: mock
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  application:
    name: raildock-server
  session:
    timeout: 30m
    jdbc:
        initialize-schema: always
springdoc:
  swagger-ui:
    path: /docs
    with-credentials: true
  show-login-endpoint: true
server:
  servlet:
    session:
      cookie:
        max-age: 3600
logging:
  level:
    org.springframework.security: DEBUG

fastapi:
  base-url: http://fastapi:8000