spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  application:
    name: raildock-server
  session:
    timeout: 30m
    jdbc:
        initialize-schema: always
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
springdoc:
  swagger-ui:
    path: /docs
    with-credentials: true
  show-login-endpoint: true
server:
  servlet:
    session:
      cookie:
        max-age: 3600
logging:
  level:
    org.springframework.security: DEBUG

integration:
  llm:
    url: http://localhost:8000
  vision:
    url: ${VISION_URL}

aws:
  region: ap-northeast-2
  s3:
    bucket: raildock-filestorage
  cloudfront:
    domain: https://d6enbbgppxz0x.cloudfront.net

raildock:
  detect:
    scheduler:
      delay: 5000