spring:
  datasource:
    url: jdbc:mysql://db:3306/raildock?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: raildock
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  session:
    timeout: 30m
    jdbc:
      initialize-schema: always  # ✅ 처음엔 always로 테이블 자동 생성

springdoc:
  swagger-ui:
    enabled: true   # 운영에서 끌 거면 false로

fastapi:
  url: http://hsyoon14.iptime.org:18000